#Configuation for robot odometry EKF
#
frequency: 50

odom0: /curiosity_mars_rover/odom
odom0_config: [true, true, true,
               false, false, false,
               true, true, true,
               false, false, true,
               false, false, false]
odom0_differential: false

imu0: /curiosity_mars_rover/imu/data
imu0_config: [false, false, false,
              true, true, true,
              false, false, false,
              true, true, true,
              false, false, false]
imu0_differential: false

odom_frame: odom
base_link_frame: base_link
world_frame: odom

predict_to_current_time: true
