map_type: costmap
origin_z: 0.0
z_resolution: 1
z_voxels: 2

obstacle_range: 2.5
raytrace_range: 3.0

publish_voxel_map: false
transform_tolerance: 0.5
meter_scoring: true

footprint: [[-2, -2], [-2, 2], [2, 2], [2, -2]] # Todo: correct footprint
footprint_padding: 0.1

plugins:
# - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
- {name: inflater_layer, type: "costmap_2d::InflationLayer"}

# obstacles_layer:
#   observation_sources: scan1 scan2
#   scan1:
#     sensor_frame: camera_link_backhazcam_left
#     data_type: LaserScan
#     topic: '/curiosity_mars_rover/camera_backhazcam/scan'
#     marking: true
#     clearing: true
#     inf_is_valid: true
#     obstacle_range: 2.5
#     raytrace_range: 3.0
#     #min_obstacle_height: -5
#     #max_obstacle_height: 5
#   scan2:
#     sensor_frame: camera_link_fronthazcam_left
#     data_type: LaserScan
#     topic: '/curiosity_mars_rover/camera_fronthazcam/scan'
#     marking: true
#     clearing: true
#     inf_is_valid: true
#     obstacle_range: 2.5
#     raytrace_range: 3.0
#     #min_obstacle_height: -5
#     #max_obstacle_height: 5

  
inflation_layer:
  inflation_radius: 0.25
  # cost_scaling_factor: 1.0
