obstacle_range: 2.5
raytrace_range: 3.0

# Todo: correct footprint
footprint: [[-2, -2], [-2, 2], [2, 2], [2, -2]]

inflation_radius: 0.55


plugins:
- {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
- {name: inflater_layer, type: "costmap_2d::InflationLayer"}

obstacles_layer:
  observation_sources: scan1 scan2
  scan1: {sensor_frame: camera_link_backhazcam_left, data_type: PointCloud2, topic: /curiosity_mars_rover/camera_backhazcam/points2, marking: true, clearing: true, min_obstacle_height: -2, max_obstacle_height: 4, obstacle_range: 2.5, raytrace_range: 3.0}
  scan2: {sensor_frame: camera_link_fronthazcam_left, data_type: PointCloud2, topic: /curiosity_mars_rover/camera_fronthazcam/points2, marking: true, clearing: true, min_obstacle_height: -2, max_obstacle_height: 4, obstacle_range: 2.5, raytrace_range: 3.0}