# 
obstacle_range: 8
raytrace_range: 8
footprint: [[-1.6, -1.6], [-1.6, 1.6], [1.6, 1.6], [1.6, -1.6]] # Todo: correct footprint
footprint_padding: 0.01

# NOTE: Only topics that use point clouds or laser scans are currently supported 
# laser_sensor_layer:
#   observation_sources: laser
#   laser:
#     sensor_frame: laser
#     data_type: LaserScan
#     topic: '/sensors/laser'
#     marking: true
#     clearing: true
#     inf_is_valid: true
#     min_obstacle_height: -5
#     max_obstacle_height: 5

obstacles_layer:
  observation_sources: scan1 scan2
  scan1: {sensor_frame: camera_link_backhazcam_left, data_type: PointCloud2, topic: /curiosity_mars_rover/camera_backhazcam/points2, marking: true, clearing: true, min_obstacle_height: 0.2, max_obstacle_height: 4, obstacle_range: 4, raytrace_range: 3.0}
  scan2: {sensor_frame: camera_link_fronthazcam_left, data_type: PointCloud2, topic: /curiosity_mars_rover/camera_fronthazcam/points2, marking: true, clearing: true, min_obstacle_height: 0.2, max_obstacle_height: 4, obstacle_range: 4, raytrace_range: 3.0}
  scan3: {sensor_frame: camera_link_navcam_left, data_type: PointCloud2, topic: /curiosity_mars_rover/camera_navcam/points2, marking: true, clearing: true, min_obstacle_height: 0.1, max_obstacle_height: 4, obstacle_range: 2.5, raytrace_range: 3.0}

inflation_layer:
  inflation_radius: 0.4
  # cost_scaling_factor: 1.0

# obstacles_layer:
#   observation_sources: scan1 scan2
#   scan1:
#     sensor_frame: camera_link_backhazcam_left
#     data_type: LaserScan
#     topic: '/curiosity_mars_rover/camera_backhazcam/scan'
#     marking: true
#     clearing: true
#     inf_is_valid: true
#   scan2:
#     sensor_frame: camera_link_fronthazcam_left
#     data_type: LaserScan
#     topic: '/curiosity_mars_rover/camera_fronthazcam/scan'
#     marking: true
#     clearing: true
#     inf_is_valid: true
