map_type: costmap
origin_z: 0.0
z_resolution: 1
z_voxels: 2

obstacle_range: 8
raytrace_range: 8

publish_voxel_map: false
transform_tolerance: 0.5
meter_scoring: true

footprint: [[-1.6, -1.6], [-1.6, 1.6], [1.6, 1.6], [1.6, -1.6]] # Todo: correct footprint
footprint_padding: 0.01

plugins:
- {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
# - {name: voxel_layer, type: "costmap_2d::VoxelLayer"}
- {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacles_layer:
  observation_sources: scan2 #scan3
  # scan1:
  #   sensor_frame: camera_link_backhazcam
  #   data_type: LaserScan
  #   topic: '/curiosity_mars_rover/camera_backhazcam/scan'
  #   marking: true
  #   clearing: true
  #   inf_is_valid: true
  # scan2:
  #   sensor_frame: camera_link_fronthazcam
  #   data_type: LaserScan
  #   topic: '/curiosity_mars_rover/camera_fronthazcam/scan'
  #   marking: true
  #   clearing: true
  #   inf_is_valid: true
  # scan1:
  #   sensor_frame: camera_link_backhazcam_left
  #   data_type: LaserScan
  #   topic: '/curiosity_mars_rover/camera_backhazcam/scan'
  #   marking: true
  #   clearing: true
  #   inf_is_valid: true
  scan2:
    sensor_frame: camera_link_fronthazcam_left
    data_type: LaserScan
    topic: '/curiosity_mars_rover/camera_fronthazcam/scan'
    marking: true
    clearing: true
    inf_is_valid: true

  # scan1: {sensor_frame: camera_link_backhazcam_left, data_type: PointCloud, topic: /curiosity_mars_rover/camera_backhazcam/depth/points, marking: true, clearing: true, min_obstacle_height: 0.2, max_obstacle_height: 4, obstacle_range: 4, raytrace_range: 3.0}
  # scan2: {sensor_frame: camera_link_fronthazcam_left, data_type: PointCloud, topic: /curiosity_mars_rover/camera_fronthazcam/depth/points, marking: true, clearing: true, min_obstacle_height: 0.2, max_obstacle_height: 4, obstacle_range: 4, raytrace_range: 3.0}
  # scan3: {sensor_frame: camera_link_navcam_left, data_type: PointCloud, topic: /curiosity_mars_rover/camera_navcam/depth/points, marking: true, clearing: true, min_obstacle_height: 1.2, max_obstacle_height: 4, obstacle_range: 2.5, raytrace_range: 3.0}
  # scan1: {sensor_frame: camera_link_backhazcam_left, data_type: PointCloud2, topic: /curiosity_mars_rover/camera_backhazcam/points2, marking: true, clearing: true, min_obstacle_height: 0.2, max_obstacle_height: 4, obstacle_range: 4, raytrace_range: 3.0}
  # scan2: {sensor_frame: camera_link_fronthazcam_left, data_type: PointCloud2, topic: /curiosity_mars_rover/camera_fronthazcam/points2, marking: true, clearing: true, min_obstacle_height: 0.2, max_obstacle_height: 4, obstacle_range: 4, raytrace_range: 3.0}
  # scan3: {sensor_frame: camera_link_navcam_left, data_type: PointCloud2, topic: /curiosity_mars_rover/camera_navcam/points2, marking: true, clearing: true, min_obstacle_height: 1.2, max_obstacle_height: 4, obstacle_range: 2.5, raytrace_range: 3.0}

voxel_layer:
  publish_voxel_map: true
  observation_sources: scan1 scan2 #scan3
  # scan1:
  #   sensor_frame: camera_link_backhazcam
  #   data_type: LaserScan
  #   topic: '/curiosity_mars_rover/camera_backhazcam/scan'
  #   marking: true
  #   clearing: true
  #   inf_is_valid: true
  # scan2:
  #   sensor_frame: camera_link_fronthazcam
  #   data_type: LaserScan
  #   topic: '/curiosity_mars_rover/camera_fronthazcam/scan'
  #   marking: true
  #   clearing: true
  #   inf_is_valid: true
  scan1:
    sensor_frame: camera_link_backhazcam_left
    data_type: LaserScan
    topic: '/curiosity_mars_rover/camera_backhazcam/scan'
    marking: true
    clearing: true
    inf_is_valid: true
    min_obstacle_height: -4
    max_obstacle_height: 8
  scan2:
    sensor_frame: camera_link_fronthazcam_left
    data_type: LaserScan
    topic: '/curiosity_mars_rover/camera_fronthazcam/scan'
    marking: true
    clearing: true
    inf_is_valid: true
    min_obstacle_height: -4
    max_obstacle_height: 8

inflation_layer:
  inflation_radius: 3.0

